# Site settings
title: Jorge Velez blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://JorgeV92.github.io"
twitter_username: Velez
github_username:  Velez

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
